### ISSUE TITLE
Won't Write Data into Master Database

### ISSUE THREAD

**Issue by briankgarland** [waughn/data-exchange-restful-provider#3]
Based on what I'm seeing in Fiddler, the API call is working. But my data never gets written. The log just shows the process starting and stopping, in about a second, but no errors. I'm wondering if the format of my JSON might be a problem. Especially given the Path Expression in the Read pipeline. I'm using "Person" but in the JSON there is actually a top level called "Employees". Using either one makes no difference though.

![image](https://user-images.githubusercontent.com/9375476/66585983-1343ec00-eb45-11e9-8cc8-300d8415f61e.png)
![image](https://user-images.githubusercontent.com/9375476/66586021-28207f80-eb45-11e9-8d01-526f1a4ae77d.png)

**Comment by waughn** [comment]
Try `Employees.Person` in the Path Expression field.

**Comment by briankgarland** [comment]
No luck. I think I’ll just need to code it. Thanks for the reply.
